"""create DB

Revision ID: 72a70d540fab
Revises: 
Create Date: 2022-12-25 03:32:06.374373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a70d540fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respondent_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.Column('means1', sa.String(length=200), nullable=True),
    sa.Column('desires', sa.String(length=200), nullable=True),
    sa.Column('preference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['res_id'], ['respondent_data.id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('respondent_data')
    # ### end Alembic commands ###
